Add commands and keyboard shortcuts for the pipe and assignment operators
posit-dev/positron pull request #1191
Opened 2023-08-29 01:47 UTC by jennybc

Addresses #1187

Refinements I foresee for the future:

* Currently the default pipe is `|>`. It would be better to default to `|>` for R >= 4.1 and `%>%` otherwise. Things are still usable today, because this is already configurable at the user or workspace level. I still think the current implementation is a big improvement over nothing.
* ~By implementing the insertion of `<-` as a simple keybinding (`"command": "type"`), I *think*  it makes it impossible/harder to surface in the command palette (since it's no longer a command, after all). This might make the existence of the keyboard shortcut harder to discover. But that will likely become less of a concern as Positron gains more keybindings and this becomes one of many.~ *It became a command after all.*

2023-08-29 03:19 UTC, juliasilge reviewed
First commands! 🎉 

I don't know if I would vote for getting fancy with whitespace at this stage in the game, given that we can use the existing `type` command. From what I can tell, RStudio doesn't do anything fancy but just plain adds in ` |> `.

I do think adding the user option for base vs. magrittr pipe is a good way to go. 👍 If you write a little function to get the user option, it could be developed more later to be fancy about the current R version. (I think currently you'd have to use `positron.runtime.getRunningRuntimes()` and then get the version out of the metadata.)

2023-08-30 17:29 UTC, jmcphers requested changes

2023-08-30 18:29 UTC, DavisVaughan approved these changes
Nice!

<img width="817" alt="Screenshot 2023-08-30 at 2 27 56 PM" src="https://github.com/posit-dev/positron/assets/19150088/8ff0e018-bdd0-4c6f-9a8e-ca14b1edf96e">


https://github.com/posit-dev/positron/assets/19150088/d5b81196-29bf-4fce-bd51-58a1506525da

2023-08-30 19:10 UTC, jmcphers approved these changes
LGTM!

2023-08-31 01:53 UTC, juliasilge approved these changes

2023-08-31 02:55 UTC, merged