Add support for markdown cells in positron notebooks
posit-dev/positron pull request #2563
Opened 2024-03-28 17:03 UTC by nstrayer

### Intent

Add the ability to create and edit markdown cells in notebooks. 

<img width="591" alt="image" src="https://github.com/posit-dev/positron/assets/6764693/8a6629e1-7500-415f-8696-391fecfae3f4">

### Approach

Leveraged existing markdown parser from the `markdown-language-features` extension. 

- Added new component for displaying images (`DeferredImage`) from the local file-system in react-land.
  - Uses new extension `positron-notebooks` to do so with the `'positronNotebookHelpers.convertImageToBase64'` command that converts image to data-url.
  - Updated the `renderHtml()` function to allow for the usage of custom components for a tag type. This is used to pass `<DeferredImage/>` component instead of plain `<img/>`.

- Added `<Markdown/>` component that takes a string of markdown text and renders it into react land with images done using the  `<DeferredImage/>` component

- Markup cells default to closed but can be opened via double-clicking or a "show editor" button. 

Addresses #2350

2024-03-28 17:56 UTC, seeM reviewed
(Partial review since I had to head out, will complete tomorrow.)

Very nice! It mostly worked well in my testing. A few rough edges I encountered and some thoughts below, but happy to get :

1. For some reason the "Hide Editor" button didn't initially work for me, but then started working and I'm not sure what changed.
2. I also managed to make my notebook tab go blank although I'm not sure how. I _think_ I tried to close the tab (but it didn't actually close) then created a markdown cell and added an image to it.
3. Links are not yet clickable.
4. We'll want to decide which approach we take in terms of showing a side-by-side preview versus previewing when the user tries to "run" the cell, but we can handle that in future.

We can address some of these in follow-ups of course.

2024-03-28 23:28 UTC, jmcphers requested changes

2024-04-01 18:20 UTC, softwarenerd approved these changes
I found just one small thing.

2024-04-01 19:22 UTC, jmcphers approved these changes

2024-04-01 19:54 UTC, merged