Connections pane integration with the variables pane
posit-dev/positron pull request #2594
Opened 2024-04-01 19:37 UTC by dfalbel

### Intent

This PR integrates the variables pane with the connections pane. When variables are assigned and they are known to the connections pane we display a small icon, that triggers the registration of that connection with the connections pane.
Addresses https://github.com/posit-dev/positron/issues/2503

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

1. Added a new inspector that catches supported connections and enables the `view` buttom for them:

https://github.com/posit-dev/positron/blob/f233f3ee41366f6f9110abc16310e3418f4b7300/extensions/positron-python/pythonFiles/positron/positron_ipykernel/inspectors.py#L902-L909

2. Made the variables pane preview handling depend on the type of object, and for supported values we will
    enable register the object with the connections service:

https://github.com/posit-dev/positron/blob/f233f3ee41366f6f9110abc16310e3418f4b7300/extensions/positron-python/pythonFiles/positron/positron_ipykernel/variables.py#L519-L537

 3. Add listeners to variable updates/deletions in the variables service allowing the connections service to handle those events, if required.

https://github.com/posit-dev/positron/blob/f233f3ee41366f6f9110abc16310e3418f4b7300/extensions/positron-python/pythonFiles/positron/positron_ipykernel/variables.py#L157-L169

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues.

A small video below showing different scenarios that we expect this PR to work with:

https://github.com/posit-dev/positron/assets/4706822/a08050c9-b84d-4b35-a804-fe051f201b9d

2024-04-04 22:26 UTC, isabelizimm reviewed
Some random teeny nits, but overall, this works really nicely for Python 3.10+! It looks like `sqlite3` Connections are not registering on Python 3.9 and lower. I took a look at the different versions [(this is the diff of 3.9 and 3.10)](https://github.com/python/cpython/compare/3.9...3.10), but wasn't quite sure where to look. There's not much actual Python code there, so it's probably somewhere on the C side, under `Modules/_sqlite` 😅 

One more random thing: when users click on the DB icon in the Variables pane, should it bring focus to the Connections pane ?

2024-04-10 19:45 UTC, isabelizimm approved these changes
This looks good for the supported versions of Python! It also feels much faster than before ☄️ 

One small thing-- if you have a Connection open and then shut down the runtime (without disconnecting), you'll get this in the logs:

```
[Python]   File "/Users/isabelzimmerman/code/positron/extensions/positron-python/python_files/positron/positron_ipykernel/positron_ipkernel.py", line 374, in do_shutdown
[Python]     self.connections_service.shutdown()
[Python]   File "/Users/isabelzimmerman/code/positron/extensions/positron-python/python_files/positron/positron_ipykernel/connections.py", line 346, in shutdown
[Python]     for comm_id in self.comms.keys():
[Python] RuntimeError: dictionary changed size during iteration
```

I think if you change that line to `list(self.comms.keys())` it should be good!

2024-04-18 00:13 UTC, jmcphers requested changes
Nice!

One thing that isn't clear to me is why we need the `createEventEmitter` bits. It looks like they are duplicating the codegen'ed event `onDidFocus`. If you want to expose that event in ConnectionsComm, you can do so just by creating a public-facing `Event` and then assigning it to the wrapped `onDidFocus` from the generated class.

2024-04-18 15:18 UTC, jmcphers approved these changes

2024-04-18 18:00 UTC, merged