Add new 'r.rmarkdownRender' command
posit-dev/positron pull request #3308
Opened 2024-05-29 21:33 UTC by juliasilge

### Intent

Addresses #1421 by adding a command to do `rmarkdown::render()` in a fresh R session (i.e. R terminal)

### Approach

This PR adds a command that is similar to `'r.sourceCurrentFile'` but checks to see if rmarkdown is installed and runs it in a new terminal.

### QA Notes

We should check how this command works both with/without the Quarto extension installed. It contributes both a command to the command palette and to the "editor/title/run" bar, but only for `.Rmd` and not `.qmd`. The `'r.sourceCurrentFile'` command should all still work as expected.

You can make a file saved as `.Rmd` such as this:

````markdown
---
title: "A wonderful R Markdown document"
output:
  html_document:
    math_method: katex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

Here is some math:

$1 + 1$

You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
````

2024-05-29 22:29 UTC, juliasilge reviewed
This PR does not provide support for _previewing_ any R Markdown, only doing `rmarkdown::render()`.

2024-05-30 03:14 UTC, jmcphers requested changes

2024-05-30 17:19 UTC, jmcphers approved these changes

2024-05-30 17:22 UTC, merged

2024-08-22 22:52 UTC, CorradoLanera commented
@juliasilge, when trying to preview an md/Rmd file, Positron signals an error requiring a version of Quarto greater than 1.5.39 even though it has installed and activated the 1.114.0.

![image](https://github.com/user-attachments/assets/7818141a-b1e3-4823-b30f-c74e96bc660e)

```
Positron Version: 2024.08.0 (system setup) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T03:30:12.447Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26120
```