do not refresh on first open
posit-dev/positron pull request #4462
Opened 2024-08-23 15:07 UTC by isabelizimm

### QA Notes

2024-08-28 18:21 UTC, isabelizimm commented
not quite sure what is happening with the venv/debugger tests, they seem to hang forever--I am able to run them locally

2024-08-29 11:48 UTC, seeM approved these changes
Code changes look good! Scenario 1 works as expected locally, but scenario 2 doesn't. I have to manually refresh for it to show up. I used a different env name in scenario 2 vs 1, maybe related?

I think the test failure may be related to a change in this PR since I haven't seen the failure before. There's an error:

```
Error: Failed to initialize Python extension for tests after 3 minutes
    at activatePythonExtensionScript (/Users/runner/work/positron/positron/path with spaces/extensions/positron-python/out/test/index.js:58:16)
    at Object.run (/Users/runner/work/positron/positron/path with spaces/extensions/positron-python/out/test/index.js:85:15)
```

I wonder if that has to do with removing interpreter refresh? Some of the test helpers might be assuming it happens and awaiting something

2024-08-29 11:50 UTC, seeM requested changes
Oops, previous review should've been "Request Changes" because of the hanging test.

2024-08-30 13:38 UTC, isabelizimm commented
> Scenario 1 works as expected locally, but scenario 2 doesn't. 

Updated to refresh on extension activation; so both scenarios should work now! That was the problem with the tests hanging as well, waiting for the refresh  👍  This does not impact the selection of the interpreter, that will start up and interpreter discovery will continue in the background.

2024-08-30 13:47 UTC, seeM commented on extensions/positron-python/src/client/pythonEnvironments/index.ts
> +
```suggestion
```

2024-08-30 14:04 UTC, seeM submitted a review, later dismissed

2024-08-30 17:20 UTC, merged