Don't show Bokeh GlyphRenderer() messages in plots pane
posit-dev/positron pull request #4598
Opened 2024-09-06 15:39 UTC by nstrayer

Addresses #4597

This PR overrides the `_repr_html_` method on the `GlyphRenderer` class so it doesn't output html that gets shown in the plots pane. 
This commonly happens when running line-by-line while making a bokeh plot. 

### Testing

Running the following (making sure the `p.line(...)` line is last.)

```python
from bokeh.plotting import figure, show
p = figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Temp.", line_width=2)
```
Should no longer print an ugly `GlyphRenderer(...)` message to the plots pane. 

### Open question:
This just fixes the problem for `GlyphRenderer` but you can also still get similar style "plots" for anything in bokeh that inherits from the `Model` base class. This includes things like `Figure`. You can run the following line:
```python
from bokeh.plotting import figure, show
figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
```
You should get a plot pane just like the `GlyphRenderer`. A way to get around this is to simply disable the `_repr_html_` method for the whole `Model` class, which works fine but may be a bit heavy-handed.

2024-09-06 15:40 UTC, nstrayer commented
Just need to add a unit test and I'll take this off draft.

2024-09-06 20:53 UTC, isabelizimm commented on extensions/positron-python/python_files/positron/positron_ipykernel/patch/bokeh.py
> +        renderers.GlyphRenderer._repr_html_ = empty_repr_html
will this disable the GlyphRenderer inside the html output for the plot itself?

2024-09-09 13:40 UTC, seeM requested changes
With empty `text/html`, nothing is displayed in the console at all, not even the `text/plain`. Maybe `del`ing the `_repr_html_` method will still let the `text/plain` take priority.

Should we do this to the base `Model` class instead of `GlyphRenderer`? I'm not sure we'll want the default behavior for any subclass.

2024-09-09 13:46 UTC, seeM commented
There is this little interaction of `Model`s as well. I'm not sure how many people would want it, but it will currently work in a notebook. What do you think about showing these things in the Viewer pane? I'm not actually sure if that would be a good experience but thought it's worth discussing.

https://github.com/user-attachments/assets/f7daa999-960e-4cb0-b310-68f01c7e023d

2024-09-12 13:22 UTC, seeM approved these changes, later dismissed
LGTM!

2024-09-13 15:56 UTC, nstrayer commented on extensions/positron-python/python_files/pyproject.toml
> +
```suggestion
```

2024-09-13 15:58 UTC, merged