(Start to) handle cli hyperlinks in the terminal used for pkg dev tasks
posit-dev/positron pull request #5231
Opened 2024-10-31 03:55 UTC by jennybc

Still WIP, because negotiations need to happen with cli

### QA Notes

*none yet*

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/package.json
> +      },
Will go away. Purely a development convenience, before I modified cli the way I needed.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/package.json
> +  ]
Will go away. Purely a development convenience, when convincing myself that we could see OSC 8 hyperlinks.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/package.nls.json
> +	"r.command.cliHyperlinks.title": "Emit cli hyperlinks",
Will go away.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/package.nls.json
> +	"r.menu.cliHyperlinks.title": "Emit cli hyperlinks",
Will go away.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/src/commands.ts
> +
Will go away.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/src/extension.ts
> +	context.subscriptions.push(disposable);
Will go away. Purely a development convenience, when convincing myself that we could see OSC 8 hyperlinks.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/src/extension.ts
> +	vscode.window.showInformationMessage(`URI Details:\n${uriDetailsJson}`);
Will go away. A development convenience.

2024-10-31 04:02 UTC, jennybc commented on extensions/positron-r/src/tasks.ts
> +			task: 'r.task.cliHyperlinks',
Will go away.

2024-11-18 20:58 UTC, jennybc commented on extensions/positron-r/package.json
> +  "publisher": "positron",
From #5268, we're going to use "positron" as publisher here.

2024-11-19 22:25 UTC, juliasilge requested changes
This is working well for me! 🎉 

My main question is about the file hyperlinks. I understand that this PR is not meant to address those but it leaves us in a state where _both_ kinds of hyperlinks look like you should click them but clicking one kind results in something nice and clicking another kind results in something QUITE UNPLEASANT. Is it possible not to make file hyperlinks clickable, since we're not yet handling them? If not, can we put this new feature behind a feature flag until https://github.com/posit-dev/positron/issues/5409 is resolved? Right now we have landed a combo of "looks just like what I _should_ click" plus "both surprising and awful result".

2024-11-20 01:38 UTC, jennybc commented
Unfortunately it's not (yet?) possible to have the run/help/vignette hyperlinks *but not have* file hyperlinks. At least, AFAIK, it's not possible and I'm pretty up to speed on this part of cli right now.

I feel like we can safely merge and I will tackle #5409 in the near term. This is behind an implicit feature flag of sorts, in that we only activate the hyperlinks in the presence of truly bleeding edge cli (version 3.6.3.9001). It's not just any dev version, but a dev version I bumped to specifically for this (https://github.com/r-lib/cli/commit/9d6e9db195d2bb1e7231d467dec2e0571f81f48d). I think the few people who might install this version of cli can probably cope for the couple weeks until file hyperlinks fully catch up.

Plus, as an experiment, I just changed the macOS file affiliation for `.R` from RStudio to Positron and this also "solves" the problem right away.

2024-11-20 03:01 UTC, jennybc commented on extensions/positron-r/src/uri-handler.ts
> +	}
Here's where we exit early, without activating hyperlinks in the integrated terminal, in the absence of bleeding edge cli.

2024-11-20 03:45 UTC, juliasilge approved these changes, later dismissed
> This is behind an implicit feature flag of sorts, in that we only activate the hyperlinks in the presence of truly bleeding edge cli (version 3.6.3.9001). 

I am not a fan of this getting merged into main as is, but this is a fair point. Can you confirm with Gabor and take on making sure that we do not get a surprise cli release before the file hyperlinks are fixed up?

Alternatively, you could [throw a quick `IsDevelopmentContext` around this](https://connect.posit.it/positron-wiki/feature-flagging.html#development-builds-only) to gate it from being exposed to users as is?

2024-11-21 20:23 UTC, jennybc commented
Yes @gaborcsardi has confirmed there will be no surprise cli release.

I don't love the idea of the "dev build only" gate, because I am hoping to use this in my package dev work. If if we think it needs to be gated, I could add a setting for it.

2024-11-24 20:49 UTC, jennybc commented
Feature flag is in.

2024-11-24 22:48 UTC, juliasilge approved these changes

2024-11-25 05:50 UTC, merged