New function to expose more info about an installed package
posit-dev/positron pull request #5365
Opened 2024-11-13 23:52 UTC by jennybc

Addresses #1957

What's the payoff?

* Sometimes you want to get info about a package version without necessarily challenging the user to install/upgrade. (I need this to finish #5231, for example). 
* If you do need to invite the user to install or upgrade a package, this extra info allows us to build a better message.

I also removed the caching, because gathering this extra info makes that increasingly awkward. If we're worried about performance, I have some hypotheses about other things that we could refactor with a bigger payoff. In any case, we'd need to get some user reports and/or collect data.

### QA Notes

To experience that `checkInstalled()` still works and to see the user-facing message in the absence of a minimum version requirement, here's one idea:

* Remove the styler package: `remove.packages("styler")`
* Trigger the *Format Document* command

You should see this:

<img width="404" alt="Screenshot 2024-11-13 at 3 46 39 PM" src="https://github.com/user-attachments/assets/2231ec70-d335-4f99-b5f9-598cd1c19301">

To experience that `checkInstalled()` still works and to see the user-facing message in the presence of a minimum version requirement, here's on idea:

* Install renv at a version below positron-r's minimum version, which is currently 1.0.9. I would do this with `pak::pak("renv@1.0.8")`.
* Walk through *File > New Project > R Project* and click the box to use renv:

  <img width="701" alt="Screenshot 2024-11-13 at 3 35 45 PM" src="https://github.com/user-attachments/assets/430908cb-9fce-43fe-8d39-a6fec56f9a70">

As the new project is being stood up, you should see this:

<img width="401" alt="Screenshot 2024-11-13 at 3 37 12 PM" src="https://github.com/user-attachments/assets/ee3d82a1-5479-47e6-82bd-a693583d2f4a">

2024-11-14 20:10 UTC, juliasilge reviewed
I tend to think we want to keep the per-session cache of what we have already looked up, given that this goes all the way through to the R session and we call this every time we install, check, document, etc.

Were you thinking differently about this?

2024-11-14 20:30 UTC, jennybc commented
I'm going to bring caching back with a bit of modification. Stay tuned.

2024-11-15 23:33 UTC, jennybc commented on extensions/positron-r/src/session.ts
> +		return compatible;
This is a bit new: previously we always assumed that our attempt to install/update the package was successful. Now we check that specifically, cache new version info, and return the result (hopefully `true`).

2024-11-15 23:36 UTC, jennybc commented
OK @juliasilge this is done, now, complete with restored and upgraded caching. Additional work that is not shown here: I temporarily added lots of logging to verify that the cache was being used/updated as expected and I was satisfied with the results.

2024-11-16 01:16 UTC, juliasilge requested changes
I think something here isn't quite working right yet.

With our current release build, if I try to create a new project using renv but I have renv 1.0.8 installed, I see this:

![Screenshot 2024-11-15 at 6 10 36 PM](https://github.com/user-attachments/assets/e31e85a7-4db9-4920-b1a4-14d6954a2f23)

With a dev build in the same situation, the new project opens up but there is no message or prompt to install renv.

Maybe it's just that ark needs to be bumped in this PR?

2024-11-16 01:16 UTC, juliasilge commented on extensions/positron-r/src/session.ts
> +	// eslint-disable-next-line @typescript-eslint/naming-convention
Thank you so much 😭

2024-11-16 01:38 UTC, jennybc commented
I have already rebased and force pushed this PR branch to include the ark version bump I did earlier today. Do you need to refetch this branch? Any chance you've got a local ark build that's getting used in the dev build instead of the 0.1.154 release from this afternoon?

2024-11-16 01:40 UTC, jennybc commented
I just re-did the QA step described above and I'm still getting the desired pop-up:

<img width="1021" alt="Screenshot 2024-11-15 at 5 39 58 PM" src="https://github.com/user-attachments/assets/dd589433-8f98-430e-b721-c737fdb72863">

2024-11-16 02:02 UTC, juliasilge commented
I think it's possible what we need is step 4 [here](https://connect.posit.it/positron-wiki/updating-amalthea.html#pushing-kernel-updates), like [this commit](https://github.com/posit-dev/positron/pull/4606/commits/25eb1eb6829f5ed6e9f83b745cd4c6dc8ea29c86).

2024-11-16 03:08 UTC, jennybc commented
🤔 step 4 has happened, in `main`, in 34695a1276d865021bc4ffaac5a0746615956341. And this PR is rebased on that.

Here's the ark requirement in `positron/extensions/positron-r/package.json` in this branch:

https://github.com/posit-dev/positron/blob/d0e363d222ac0d6936be3925281902a5be82a2ee/extensions/positron-r/package.json#L673

It does feel like an ark mismatch. Does `.ps.ark.version()` report 0.1.154 in your dev build?

2024-11-16 03:12 UTC, jennybc commented
I made one more change, but it would not explain what you're seeing (a complete lack of prompt).

2024-11-18 00:01 UTC, juliasilge approved these changes
I did a full `rebuild.sh` and now see the correct prompt:

![Screenshot 2024-11-17 at 4 59 07 PM](https://github.com/user-attachments/assets/8b8a907c-0852-4f0a-94c2-dc9b5914cb88)

I'm not totally sure what the problem was (no local build of ark, etc) but thank you for your patience!

2024-11-18 16:48 UTC, merged