Switch to overlay webviews for notebooks
posit-dev/positron pull request #5829
Opened 2024-12-19 14:03 UTC by nstrayer

Addresses #5491 

This PR changes how we render html output in notebooks 2.0 by switching to overlay webviews instead of standard ones. 
The reason for this switch was that there is no way to preserve the content of the webview across visibility changes with standard webviews. This means we would have to fully re-render every output every time the user switched to the notebook view. 

One benefit of this switch is we were able to remove all the logic surrounding different webview types being returned from the various webview services, simplifying the API a good bit. 

### QA Notes

- Dynamic plots like hvplot should still show up as expected. 
- You should be able to navigate away from the notebook and back and the plot should reappear in the same state it was in. 
- Plots should never spill out of the notebook containment. (e.g. be visible when the notebook isnt. This is an annoying problem with overlay webviews that we've had to deal with before in the plots pane etc..)

2024-12-19 15:02 UTC, seeM requested changes
I checked out the branch and played around with it a bit and found a few issues.

In a notebook with two cells:

```python
import hvplot.pandas
import pandas as pd
```

```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x='sepal_width', y='sepal_length')
fig
```

1. The plot seems to be placed over the cell selection border, see the section in the red box:

    ![](https://github.com/user-attachments/assets/9226d32b-ef6f-4d36-bb67-70e5f68c60f1)
2. The plot remains if I switch between two notebooks:

    https://github.com/user-attachments/assets/d568c813-54d1-4353-a7a6-737d5dfca876
3. There's a similar issue when showing/hiding the bottom pane with Cmd+J:

    https://github.com/user-attachments/assets/b105ada8-7a25-4e47-9b15-f5b4657efbd8

2024-12-19 22:15 UTC, nstrayer commented
@ntluong95 , see #5495 and there is a simple running animation (a pulsing border around the cell executing). 

Feel free to make a new issue for the cell execution animation with ideas about it - it's a tricky problem and we'd love your input! Also reacting to the other issue can help us prioritize! Currently we're focusing on the underpinnings of the current notebooks to get them rock solid before making a big push on these experimental notebooks.

2024-12-20 15:07 UTC, nstrayer commented
@seeM I couldn't reproduce 1 locally but the others should be fixed. Let me know if you still have the problem with overlap.

2025-01-02 06:57 UTC, seeM reviewed
It unfortunately isn't showing at all now:

https://github.com/user-attachments/assets/8ec47dbf-e8be-4bf0-9a14-397969ded883

Happy to merge this now since it's already behind a feature flag, and do any additional work once you're back.

E2E tests pass too: https://github.com/posit-dev/positron/actions/runs/12578730237.

2025-01-02 08:09 UTC, seeM approved these changes

2025-01-02 08:11 UTC, merged