Configure cli file hyperlinks for R package dev tasks
posit-dev/positron pull request #5850
Opened 2024-12-21 00:37 UTC by jennybc

Addresses #5409

*Best to wait for https://github.com/r-lib/cli/pull/744/commits to be merged*

### QA Notes

*I'll come back with before removing the draft status.*

2025-01-13 15:43 UTC, juliasilge approved these changes
This is working well for me!

Just to document a bit here, there are quite a few popups that folks will need to accept to get this to work:

![Screenshot 2025-01-13 at 8 41 36 AM](https://github.com/user-attachments/assets/42555d6d-e330-4bc4-8192-903ea0dcefa7)

2025-01-13 15:56 UTC, juliasilge requested changes
Ah actually, I've got one more request. Can you [add the tag for R package tests](https://github.com/posit-dev/positron/blob/main/test/e2e/infra/test-runner/test-tags.ts) to this PR, to run those specific tests? More info at:

<https://github.com/posit-dev/positron/blob/main/test/e2e/README.md#pull-requests-and-test-tags>

2025-01-13 19:29 UTC, jennybc commented
@juliasilge I think I've successfully added the correct tag. And yet no new test run has happened. Is there some additional step? Do I just need to ... push an empty commit?

2025-01-13 19:38 UTC, juliasilge commented
I believe you can either push an empty commit or click to rerun the jobs.

2025-01-13 19:38 UTC, jennybc commented
I just did rerun all jobs.

2025-01-13 20:05 UTC, jennybc commented
The test run passed ✅

2025-01-14 03:14 UTC, juliasilge approved these changes
Thank you so much!

2025-01-14 03:17 UTC, merged